									<div class="row">
										<div class="col-md-6">
											<div class="panel panel-default">
												<header class="panel-heading">
													Поиск автомобиля по VIN
												</header>
												<div class="panel-body">
													<form action="<?=$this->url->get("catalog")?>" method="get" role="form">
														<input type="hidden" name="action" value="vin">
														<div class="form-group">
															<label for="vin">Введите VIN (17 знаков)</label>
															<input class="form-control" placeholder="VIN" type="text" name="vin" id="vin">
															<span class="help-block m-b-none">Например: WAUBH54B11N111054</span>
														</div>
														<button type="submit" class="btn btn-sm btn-default">Найти</button>
													</form>
												</div>
											</div>
										</div>
										<div class="col-md-6">
											<div class="panel panel-default">
												<header class="panel-heading">
													Поиск автомобиля по номеру кузова
												</header>
												<div class="panel-body">
													<form action="<?=$this->url->get("catalog")?>" method="get" role="form">
														<input type="hidden" name="action" value="frame">
														<div class="form-group">
															<label for="frame">Введите код и номер кузова</label>
															<div class="row">
																<div class="col-sm-6">
																	<input class="form-control" type="text" placeholder="Код кузова" name="frame" id="frame">
																</div>
																<div class="col-sm-6">
																	<input class="form-control" type="text" placeholder="Номер кузова" name="frameNo" id="frameNo">
																</div>
															</div>
															<span class="help-block m-b-none">Например: FNN15-502358</span>
														</div>
														<button type="submit" class="btn btn-sm btn-default">Найти</button>
													</form>
												</div>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-12">
											<section class="panel panel-default">
												<header class="panel-heading">
													Выберите марку
												</header>
												<table class="table table-striped m-b-none">
													<thead>
														<tr>
															<th style="width: 50px;">CODE</th>
															<th>Название</th>
														</tr>
													</thead>
													<tbody>
                                                    <?php if(!empty($catalogs)): ?>
														<?foreach( $catalogs->children() AS $catalog ):?> 
														<tr>
															<td>
																<a data-bjax href="<?=$this->url->get("catalog", array("action" => "catalog", "code" => $catalog->attributes()->code->__toString()))?>">
																	<?=$catalog->attributes()["code"]?>
																</a>
															</td>
															<td>
																<a data-bjax href="<?=$this->url->get("catalog", array("action" => "catalog", "code" => $catalog->attributes()->code->__toString()))?>">
																	<?=$catalog->attributes()["name"]?>
																</a>
															</td>
														</tr>
														<?endforeach;?>
                                                    <?php else: ?>
                                                    <tr>
                                                        <td>#</td>
                                                        <td>Информация отсутсвует</td>
                                                    </tr>
                                                    <?php endif; ?>
													</tbody>
												</table>
											</section>
										</div>
									</div>