												<ul class="nav">
													<?foreach( $item->children() AS $item ):?> 
													<li>
														<a href="#" data-queryparams="<?=htmlspecialchars(json_encode(array(
															"id" => $item->attributes()["quickgroupid"]->__toString(),
															"link" => ($item->attributes()["link"]->__toString()=="true"?true:false),
															"code" => $catalogCode,
															"vid" => $vid,
															"ssd" => $ssd,
														)))?>">
															<?if( count($item->children()) > 0 ):?> 
															<i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>
															<?endif;?> 
															<?=$item->attributes()["name"]?>
														</a>
														<?if( count($item->children()) > 0 ):?> 
														<?=$this->partial("catalog/pages/findMenu")?> 
														<?endif;?> 
													</li>
													<?endforeach;?> 
												</ul>