<?$this->assets
	->collection("footer")
	->addJs("assets/js/catalog/find.js");?>
									<div class="panel panel-default text-sm doc-buttons">
										<div class="panel-body">
											<button class="btn btn-sm btn-default" disabled>Быстрый поиск</button>
											<a href="<?=$this->url->get("catalog", array(
												"action" => "units",
												"code" => $catalogCode,
												"vid" => $vid,
												"ssd" => $ssd,
											))?>" class="btn btn-sm btn-default">Поиск по узлам</a>
										</div>
									</div>
									<section class="hbox stretch">
										<aside class="aside-md bg-light dker b-r">
											<style>
											aside .nav .active > a {
												text-decoration: none;
												background-color: #eee;
											}
											aside .nav .nav {
												display: none;
											}
											aside .nav .nav li a {
												font-size: 11px;
											}
											aside .nav .active > .nav {
												display: block;
												padding-left: 5px;
											}
											</style>
											<ul class="nav">
												<?
												$base = (count($list->children()) > 1?$list:$list->children()[0]);
												?> 
												<?foreach( $base->children() AS $item ):?> 
												<li class="b-b">
													<a href="#" data-queryparams="<?=htmlspecialchars(json_encode(array(
														"id" => $item->attributes()["quickgroupid"]->__toString(),
														"link" => ($item->attributes()["link"]->__toString()=="true"?true:false),
														"code" => $catalogCode,
														"vid" => $vid,
														"ssd" => $ssd,
													)))?>">
														<?if( count($item->children()) > 0 ):?> 
														<i class="fa fa-chevron-right pull-right m-t-xs text-xs icon-muted"></i>
														<?endif;?> 
														<?=$item->attributes()["name"]?>
													</a>
													<?if( count($item->children()) > 0 ):?> 
													<?=$this->partial("catalog/pages/findMenu")?> 
													<?endif;?> 
												</li>
												<?endforeach;?> 
											</ul>
										</aside>
										<aside role="list" style="opacity: 0;">
											<div class="col-sm-3" role="image">
												
											</div>
											<div class="col-sm-9">
												<table class="table table-striped m-b-none">
													<thead>
														<tr>
															<th style="width: 150px;">OEM</th>
															<th>Номер</th>
															<th>Название</th>
															<th>Примечание</th>
														</tr>
													</thead>
													<tbody>
														
													</tbody>
												</table>
											</div>
										</aside>
									</section>