									<div class="row">
										<div class="col-sm-12">
											<div class="panel panel-default">
												<header class="panel-heading">
													Поиск автомобиля по VIN
												</header>
												<div class="panel-body">
													<form action="<?=$this->url->get("catalog")?>" method="get" role="form">
														<input type="hidden" name="action" value="vin">
														<div class="form-group">
															<label for="vin">Введите VIN (17 знаков)</label>
															<input class="form-control" placeholder="VIN" type="text" name="vin" id="vin" value="<?=htmlspecialchars($vin)?>">
															<span class="help-block m-b-none">Например: WAUBH54B11N111054</span>
														</div>
														<button type="submit" class="btn btn-sm btn-default">Найти</button>
													</form>
												</div>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-12">
											<section class="panel panel-default">
												<header class="panel-heading">
													Результаты поиска
												</header>
												<table class="table table-striped m-b-none">
													<thead>
														<tr>
															<th style="width: 50px;">CODE</th>
															<th>Название</th>
														</tr>
													</thead>
													<tbody>
														<?if( count($results->children()) ):?> 
														<?foreach( $results->children() AS $item ):?> 
														<tr>
															<td>
																<a data-bjax href="<?=$this->url->get("catalog", array(
																	"action" => "units",
																	"code" => $item->attributes()["catalog"]->__toString(),
																	"vid" => $item->attributes()["vehicleid"]->__toString(),
																	"ssd" => $item->attributes()["ssd"]->__toString(),
																	))?>">
																	<?=$item->attributes()["vehicleid"]?>
																</a>
															</td>
															<td>
																<a data-bjax href="<?=$this->url->get("catalog", array(
																	"action" => "units",
																	"code" => $item->attributes()["catalog"]->__toString(),
																	"vid" => $item->attributes()["vehicleid"]->__toString(),
																	"ssd" => $item->attributes()["ssd"]->__toString(),
																	))?>">
																	<?=$item->attributes()["name"]?>
																</a>
															</td>
														</tr>
														<?endforeach;?> 
														<?else:?>
														<tr>
															<td colspan="3">Нет результатов</td>
														</tr> 
														<?endif;?> 
													</tbody>
												</table>
											</section>
										</div>
									</div>