<div class="footer">
    <div class="container">
        <div class="col-sm-3 menu-container">
            <ul class="footer_menu">
                <li>+7 (906)-969-3163</li>
                <li>+7 (923)-169-6867</li>
                <li>+7 (983)-357-5123</li>
                <li>e-mail: aareg99@mail.ru</li>
            </ul>
        </div>
        <div class="col-sm-3">
            <div class="menu-container">
                <ul>
                    <li class="active"><a href="/">Главная</a></li>
                    <li class=""><a href="/actions">Наши акции</a></li>
                    <li class=""><a href="/delivery">Доставка и оплата</a></li>
                    <li class=""><a href="/contacts">Наши контакты</a></li>
                </ul>			
            </div>
        </div>
        <div class="col-md-3">
            <div class="menu-container">
                <p style="font-size: 11px;">
                    Цена действительна при заказе через сайт <br>
                    Для обработки заказа необходима ПРЕДОПЛАТА. <br>
                    ВНИМАНИЕ! Информация по аналогам и кроссировкам деталей является справочной,
                    не гарантирует точной замены детали и не является основанием для возврата товара.
                    Заказывая товар по кроссам, Вы несете ответственность за правильность подбора запчастей!
                </p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="menu-container">
                <ul>
                    <li class=""><a href="https://vk.com/auto_slovo" target="blank"><i class="fa fa-vk" aria-hidden="true"></i>&nbsp Мы вконтакте</a></li>
                    <li class=""><a style="color: #fff;padding: 5px;" href="#feedback" class="btn-style" data-toggle="modal">Обратная связь</a></li>
                    <div class="clearfix"></div>
                    <div class="clearfix"></div>
                    <div class="clearfix"></div>
                    <div class="clearfix"></div>
                    <div class="clearfix"></div>
                    <div class="clearfix"></div>
                    <div class="clearfix"></div>
                    <li><p><p>© 2016 - <?= date('Y'); ?> Все права защищены.</p></p></li>
                    <div class="creat1ve">
                    </div>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="numberbody" tabindex="-1" role="dialog" aria-labelledby="feedback" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <img style="max-width: 100%;" src="https://pp.userapi.com/c840328/v840328325/72b0/7Umo410uXls.jpg" alt="">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="vinnumber" tabindex="-1" role="dialog" aria-labelledby="feedback" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <img style="max-width: 100%;" src="https://pp.userapi.com/c840328/v840328325/72a7/k_F6EWCOiGY.jpg" alt="">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="feedback" tabindex="-1" role="dialog" aria-labelledby="feedback" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h4 style="text-align:center;">Обратный звонок</h4>
                <div class="clearfix"></div>
                <form role="feedback" method="post">
                    <input class="big full" type="text" class="big" name="name" placeholder="Ваше имя">
                    <div class="clearfix"></div>
                    <input class="big full" type="text" class="big" name="phone" placeholder="Ваш номер телефона">
                    <div class="clearfix"></div>
                    <textarea name="comment" rows="8" class="full-width" placeholder="Вопрос (не обязательно)"></textarea>
                    <button class="big full" type="submit">Отправить</button>
                    <p style=" font-size:  13px; padding: 20px 0 0 0;">Нажимая кнопку отправить вы принимаете <a  target="_blank" href="/Personaldata.pdf">Согласие на обработку персональных данных</a></p>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="addcart" tabindex="-1" role="dialog" aria-labelledby="feedback" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form role="form">
                    <h4 style="text-align:center;">Добавить в корзину</h4>
                    <div class="clearfix"></div>
                    <p role="brand">TORCH</p><a href="#" target="_blank" role="article">K5RTCU11</a>
                    <p role="title">Свеча зажигания effective+u 1 шт. mazda 2 3</p>
                    <h3><e role="cartCount">1</e> <span>x</span> <e role="price">61 руб.</e> <span>=</span> <e role="finalPrice">61 руб.</e></h3>
                    <div role="count">
                        <button type="button" role="up" style="padding:5px;">+</button>
                        <input style="width: 41px;margin: 0 5px;" data-max="6" type="text" role="val" name="count" value="1">
                        <button type="button" role="down" style="padding:5px 7px;">-</button>
                    </div>
                    <br></br>
                    <p>Ваш заказ будет доставлен</p>
                    <h4 role="delivery">22 сентября</h4>
                    <br></br>
                    <button type="submit">Добавить</button>
                    <button type="button" role="cancel">Отмена</button>
                    <input type="hidden" name="code" value="">
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?= $this->partial("forms/picking") ?>