<div class="row">
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="col-sm-12">
        <div class="contact-block" style="position:  absolute;z-index:  99;background:  #fff;display:  inline-block;padding:  30px 50px;border-radius:  10px;">
            <h1>Контакты</h1>
            <p>Контакты:<br>
                Адрес. г.Барнаул, Антона Петрова, 239а<br>
                тел. 8983-357-5123 WhatsApp<br>
                8906-969-3163<br>
                8923-169-6867<br>
                e-mail: aareg99@mail.ru</p>
            <p>Если у вас есть вопросы можете их задать в форме<br> обратной связи, вам перезвонят и ответят.</p>
            <a href="#feedback" class="btn-style" data-toggle="modal" style="text-decoration:none; color:#fff;">Задать вопрос</a>
        </div>
        <div class="map">
            <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ae6ea18850558424b72eaef3a4570cc067e0d85e0f1f3ca5d8018c8ad7c06e5cd&amp;width=100%25&amp;height=570&amp;lang=ru_RU&amp;scroll=true"></script>
        </div>
    </div>
</div>
