<div class="row">
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="col-sm-3">
        <?= $this->partial("shared/leftbar") ?>
    </div>
    <div class="col-sm-6">
        <h1>Как купить</h1>
        <p>Дабавить в корзину, сделать заказ, оплатить, получить товар</p>
    </div>

</div>
