		<div class="col-sm-8 col-sm-offset-2">
			<div class="row">
				<div class="col-sm-12">
					<h3>Восстановление доступа</h3>
					<p>Мы храним пароли в зашифрованном виде и не можем восстановить ваш старый пароль.<br>
						Поэтому вам нужно создать новый пароль.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="register-container">
						<form method="post">
							<div class="row">
								<div class="col-sm-12">
									<label for="password">Новый пароль</label>
									<div class="clearfix"></div>
									<?=$form->render("password", array("class" => "big", "placeholder" => "Пароль"))?>
									<?=$form->render("passwordConfirm", array("class" => "big", "placeholder" => "Еще раз"))?>
									<?foreach( $form->getMessagesFor("password") AS $message ):?> 
									<div class="clearfix"></div>
									<label for="password" class="btn-style"><?=$message?></label>
									<?endforeach;?> 
									<?foreach( $form->getMessagesFor("passwordConfirm") AS $message ):?> 
									<div class="clearfix"></div>
									<label for="passwordConfirm" class="btn-style"><?=$message?></label>
									<?endforeach;?> 
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12">
									<button class="big" type="submit">Отправить</button>
									<div class="clearfix"></div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>