<?
$this->assets
	->collection("footer")
	->addJs("assets/js/cart.js");
?>
			<div class="row">
				<div class="col-sm-12">
					<h3>Корзина</h3>
                    <p> Цена действительна при заказе через сайт.<br>
                        Для обработки заказа необходима <strong>ПРЕДОПЛАТА.</strong> <br>
                        <strong>ВНИМАНИЕ!</strong> Информация по аналогам и кроссировкам деталей является справочной,
                        не гарантирует точной замены детали и не является основанием для возврата товара.
                        Заказывая товар по кроссам, Вы несете ответственность за правильность подбора запчастей!</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<?if( !empty($cart) ):?>
					<form method="post" action="<?=$this->url->get("cart/order")?>">
						<div class="table-container">
							<table role="cart">
								<thead>
									<tr>
										<td style="width: 10px; padding: 0px;"></td>
										<td style="width: 125px;">Производитель</td>
										<td>Название</td>
										<td style="width: 105px;">Количество</td>
										<td>Наличие</td>
										<td>Доставка</td>
										<td>Цена</td>
										<td></td>
									</tr>
								</thead>
								<tbody>
									<?$amount = 0;
									foreach( $cart AS $cartItem ):
										$amount += $cartItem["price"] * $cartItem["count"]?>
									<tr data-price="<?=$cartItem["price"]?>">
										<td style="padding: 5px;"><input type="checkbox" name="order[<?=$cartItem["code"]?>]" value="Y" checked></td>
										<td><?=$cartItem["brand"]?><br><strong><?= $cartItem["article"] ?></strong></td>
										<td><?=$cartItem["name"]?></td>
										<td role="count" style="padding: 5px;">
											<button type="button" role="up" style="padding:5px;">+</button>
											<input style="width: 41px;margin: 0 5px;" data-max="<?=$cartItem["aviable"]?>" type="text" role="val" name="count[<?=$cartItem["code"]?>]" value="<?=$cartItem["count"]?>">
											<button type="button" role="down" style="padding:5px 7px;">-</button>
										</td>
										<td><?=$cartItem["aviable"]?></td>
										<td><?=$cartItem["minDelivery"]?>&nbsp;дн.</td>
										<td><?=number_format($cartItem["price"], 0, ".", "&nbsp;")?>&nbsp;р.</td>
										<td>
											<button type="button" style="padding:5px;" role="removeFromCart" data-code="<?=$cartItem["code"]?>">Убрать из корзины</button>
										</td>
									</tr>
									<?endforeach;?>
								</tbody>
								<tfoot>
									<tr>
										<td style="padding: 5px;" colspan="5">
                                            <?php if($currentUser->groupId == 1): ?>
                                            <strong>Оформить для:</strong>
                                            <select name="users" class="chosen-select" id="users">
                                                <option value="0" selected="selected">Выберите пользователя</option>
                                                <?php foreach($users AS $user): ?>
                                                    <option value="<?= $user->id ?>"><?= $user->firstName . ' ' . $user->lastName?></option>
                                                <?php endforeach; ?>
                                            </select>
                                            <?php endif; ?>
                                            <button type="submit" class="big">Оформить заказ</button>
                                        </td>
										<td style="padding: 10px;">Итого</td>
										<td style="padding: 5px 30px;"><b><span role="amount"><?=number_format($amount, 0, ".", " ")?></span></b>&nbsp;р.</td>
									</tr>
								</tfoot>
							</table>
						</div>
						<div class="clearfix"></div>
					</form>
					<?else:?>
					<div class="empty">
						<p>Вы ещё ничего не добавили в корзину</p>
					</div>
					<?endif;?>
				</div>
			</div>
<script type="text/javascript">
    $('.chosen-select').chosen({
        no_results_text: "Не найдено",
    });
</script>
